-- Seed: seed.sql
-- Real therapist data for IndiaTherapist.com

INSERT INTO therapists (
  full_name,
  slug,
  tier,
  session_rate_cents,
  specialties,
  languages,
  therapy_types,
  bio,
  photo_url,
  education,
  experience_years,
  city,
  country,
  timezone,
  whatsapp_number,
  email,
  is_active,
  max_sessions_per_day,
  stripe_connect_id
) VALUES

-- ═══════════════════════════════════════════════════════════
-- ELITE THERAPISTS
-- ═══════════════════════════════════════════════════════════

-- Elite 1: Aekta Brahmbhatt
(
  'Aekta Brahmbhatt',
  'aekta-brahmbhatt',
  'elite',
  14100,
  ARRAY['Personal Counselling', 'Relationship Counselling', 'Career Counselling'],
  ARRAY['English', 'Hindi', 'Gujarati'],
  ARRAY['Integrative Therapy', 'Solution-Focused Therapy'],
  'Aekta Brahmbhatt is a Mumbai-based counsellor with over 22 years of experience in personal, relationship, and career counselling. She brings deep cultural understanding and a compassionate approach to every session, helping NRIs navigate the complexities of life abroad.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42619c75a7f4bf907cef.jpeg',
  'University of South Wales, UK',
  22,
  'Mumbai',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Elite 2: Sharmee M Divan
(
  'Sharmee M Divan',
  'sharmee-m-divan',
  'elite',
  12100,
  ARRAY['Anxiety', 'Conscious Parenting', 'Play Therapy', 'Emotional Healing', 'Mudra Therapy'],
  ARRAY['English', 'Hindi', 'Gujarati', 'Marathi'],
  ARRAY['Bach Flower Therapy', 'EFT', 'Gestalt Therapy', 'Mudra Therapy'],
  'Sharmee M Divan is a Mumbai-based therapist with 15+ years of experience specialising in anxiety, conscious parenting, and emotional healing. Trained at Indiana University, USA, she integrates Bach Flower Therapy, EFT, Gestalt Therapy, and Mudra Therapy into her practice.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa9eedab60e470cecb.jpeg',
  'Indiana University, USA',
  15,
  'Mumbai',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Elite 3: Dr. P T Sunderam
(
  'Dr. P T Sunderam',
  'dr-p-t-sunderam',
  'elite',
  14100,
  ARRAY['Marriage Counselling', 'Relationship Therapy', 'Parenting', 'Couples Therapy'],
  ARRAY['English', 'Tamil', 'Telugu', 'Hindi'],
  ARRAY['Couples Therapy', 'Family Systems Therapy'],
  'Dr. P T Sunderam is a Chennai-based married couples relationships expert and parenting mentor with 22+ years of experience. He helps couples rebuild trust, improve communication, and navigate the unique pressures faced by NRI families.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa4f0aebde0063a302.jpeg',
  NULL,
  22,
  'Chennai',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Elite 4: Hemalatha Swaminathan
(
  'Hemalatha Swaminathan',
  'hemalatha-swaminathan',
  'elite',
  9100,
  ARRAY['Relationship Counselling', 'Art Therapy', 'Emotional Healing', 'Couples Therapy'],
  ARRAY['English', 'Tamil', 'Hindi'],
  ARRAY['Creative Art Therapy', 'Relationship Counselling'],
  'Hemalatha Swaminathan is a Chennai-based therapist with 12+ years of experience in relationship counselling and creative art therapy. She uses innovative art-based approaches to help clients express and process emotions.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa9dbb376ff307a9ef.jpeg',
  NULL,
  12,
  'Chennai',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Elite 5: Niyatii N Shah
(
  'Niyatii N Shah',
  'niyatii-n-shah',
  'elite',
  9700,
  ARRAY['Sex Education', 'Intimacy Coaching', 'Relationship Counselling', 'Marriage Counselling', 'Couples Therapy'],
  ARRAY['English', 'Hindi', 'Gujarati'],
  ARRAY['Intimacy Coaching', 'Sex Education', 'Couples Therapy'],
  'Niyatii N Shah is a Mumbai-based sex educator and intimacy coach with 13 years of experience. She helps couples and individuals navigate intimacy challenges, sexual health, and relationship dynamics with a non-judgmental, culturally sensitive approach.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b456c9dbb371ed307b3d4.png',
  NULL,
  13,
  'Mumbai',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Elite 6: Krishnan Govindan
(
  'Krishnan Govindan',
  'krishnan-govindan',
  'elite',
  14100,
  ARRAY['Divorce Coaching', 'Life Coaching', 'Business Strategy', 'Breakup Recovery', 'Relationship Counselling'],
  ARRAY['English', 'Tamil'],
  ARRAY['Divorce Coaching', 'Life Coaching', 'Business Strategy'],
  'Krishnan Govindan is Indias first divorce coach, based in Seattle, USA. He combines life coaching and business strategy to help individuals navigate divorce, breakup recovery, and major life transitions with strength and clarity.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/685aa9b8f1a848bc1fe8873d.jpeg',
  NULL,
  NULL,
  'Seattle',
  'USA',
  'America/Los_Angeles',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- ═══════════════════════════════════════════════════════════
-- PREMIUM THERAPISTS
-- ═══════════════════════════════════════════════════════════

-- Premium 1: Suvarna Varde
(
  'Suvarna Varde',
  'suvarna-varde',
  'premium',
  7700,
  ARRAY['Relationship Therapy', 'Couples Counselling', 'Marriage Counselling', 'Communication', 'Trust Issues'],
  ARRAY['English', 'Hindi', 'Marathi'],
  ARRAY['Couples Therapy', 'Communication Skills Therapy'],
  'Suvarna Varde is a Gurgaon-based relationship therapist with 14 years of experience in couples counselling, communication challenges, and trust issues.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa4f0aeb468c63a301.jpeg',
  NULL,
  14,
  'Gurgaon',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 2: Sudeeptha Grama
(
  'Sudeeptha Grama',
  'sudeeptha-grama',
  'premium',
  6700,
  ARRAY['Anxiety', 'Work-life Balance', 'Relationship Counselling', 'Communication', 'Conflict Resolution'],
  ARRAY['English', 'Kannada'],
  ARRAY['CBT', 'Mindfulness-Based Therapy'],
  'Sudeeptha Grama is a Bengaluru-based therapist with 12 years of experience specialising in anxiety, work-life balance, and relationship conflicts.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b46e89eedaba8d570e385.png',
  NULL,
  12,
  'Bengaluru',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 3: Anisha Rafi
(
  'Anisha Rafi',
  'anisha-rafi',
  'premium',
  6700,
  ARRAY['Individual Counselling', 'Couples Therapy', 'Mentoring', 'Student Empowerment', 'Communication'],
  ARRAY['English', 'Tamil'],
  ARRAY['Individual Counselling', 'Couples Counselling', 'Corporate Training'],
  'Anisha Rafi is a Coimbatore-based counsellor with 13+ years of experience in individual and couple counselling, mentoring, corporate training, and student empowerment.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa9dbb377f4207a9ea.jpeg',
  NULL,
  13,
  'Coimbatore',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 4: Snehal Chhajed
(
  'Snehal Chhajed',
  'snehal-chhajed',
  'premium',
  6700,
  ARRAY['Anxiety', 'Depression', 'Trauma', 'Relationship Issues', 'Infidelity', 'Divorce Recovery'],
  ARRAY['English', 'Hindi', 'Marathi', 'Marwari'],
  ARRAY['Trauma-informed Therapy', 'CBT', 'Relationship Counselling'],
  'Snehal Chhajed is a Pune-based therapist with 11 years of experience helping clients through anxiety, depression, trauma, relationship issues, infidelity, and divorce recovery.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/68692af1c89afc4183b7c095.png',
  NULL,
  11,
  'Pune',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 5: Ashutosh Tiwari
(
  'Ashutosh Tiwari',
  'ashutosh-tiwari',
  'premium',
  4700,
  ARRAY['Anxiety', 'Depression', 'Trauma', 'Relationship Issues', 'Career Stress', 'Divorce Recovery'],
  ARRAY['English', 'Hindi', 'Punjabi'],
  ARRAY['CBT', 'Trauma-informed Therapy', 'Career Counselling'],
  'Ashutosh Tiwari is a Delhi-based therapist with 10 years of experience working with anxiety, depression, trauma, relationship issues, career stress, and divorce recovery.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/68692ed9e4eb736b6100c65a.jpeg',
  NULL,
  10,
  'Delhi',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 6: Sana Khullar
(
  'Sana Khullar',
  'sana-khullar',
  'premium',
  6700,
  ARRAY['Sexual Therapy', 'Couples Therapy', 'Trauma', 'Abuse'],
  ARRAY['English', 'Hindi'],
  ARRAY['Sexual Therapy', 'Couples Therapy', 'Trauma-informed Therapy'],
  'Sana Khullar is a Delhi-based therapist with 9+ years of experience in sexual therapy, couples therapy, trauma, and abuse recovery.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa9dbb37c5fe07a9ed.jpeg',
  NULL,
  9,
  'Delhi',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 7: Preeti Somani
(
  'Preeti Somani',
  'preeti-somani',
  'premium',
  5700,
  ARRAY['Relationship Counselling', 'Couples Counselling', 'Parenting', 'Stress Management'],
  ARRAY['English', 'Hindi'],
  ARRAY['Relationship Counselling', 'Parenting Support'],
  'Preeti Somani is a Delhi-based counsellor with 8+ years of experience in relationship and couple counselling, parenting concerns, and emotional distress.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/68ba768746aaaa78ee47dc3d.jpeg',
  NULL,
  8,
  'Delhi',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 8: Riddhi Deshpande
(
  'Riddhi Deshpande',
  'riddhi-deshpande',
  'premium',
  5700,
  ARRAY['Clinical Counselling', 'Immigration Counselling'],
  ARRAY['English', 'Hindi', 'Marathi'],
  ARRAY['Clinical Counselling', 'Immigration-focused Therapy'],
  'Riddhi Deshpande is a Europe-based clinical counsellor with 7+ years of experience, specialising in immigration counselling. She understands the unique mental health challenges faced by immigrants and NRIs.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b47ee9eedab3b3870e422.jpeg',
  NULL,
  7,
  'Europe',
  'Europe',
  'Europe/London',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 9: Mahi Modi
(
  'Mahi Modi',
  'mahi-modi',
  'premium',
  4700,
  ARRAY['Stress', 'Work-life Balance', 'Self-Esteem', 'Depression', 'Anxiety', 'Relationship Conflict', 'Breakup Recovery'],
  ARRAY['English', 'Hindi'],
  ARRAY['CBT', 'Mindfulness-Based Therapy', 'Positive Psychology'],
  'Mahi Modi is a California-based therapist with 5+ years of experience helping clients manage stress, work-life balance, self-esteem, mild depression and anxiety, relationship conflict, and breakup recovery.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa9dbb371d6807a9ee.png',
  NULL,
  5,
  'California',
  'USA',
  'America/Los_Angeles',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 10: Gunjan Kaur Kukreja
(
  'Gunjan Kaur Kukreja',
  'gunjan-kaur-kukreja',
  'premium',
  4700,
  ARRAY['Depression', 'Anxiety', 'Relationship Concerns', 'Self-Esteem', 'Grief', 'Divorce Recovery', 'Identity', 'Burnout', 'Addiction', 'Anger Management'],
  ARRAY['English', 'Hindi', 'Punjabi'],
  ARRAY['CBT', 'Psychodynamic Therapy', 'Grief Counselling'],
  'Gunjan Kaur Kukreja is a Delhi-based therapist with 5+ years of experience across depression, anxiety, relationship concerns, self-esteem, grief, divorce, identity, caregiving, burnout, chronic stress, attachment, addiction, anger, and mood disorders.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa9dbb37114b07a9ec.jpeg',
  NULL,
  5,
  'Delhi',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 11: Amjad Ali Mohammad
(
  'Amjad Ali Mohammad',
  'amjad-ali-mohammad',
  'premium',
  5700,
  ARRAY['Anxiety', 'Depression', 'Trauma', 'Relationship Issues', 'Career Stress', 'Infidelity', 'Divorce Recovery'],
  ARRAY['English', 'Hindi', 'Telugu', 'Urdu'],
  ARRAY['CBT', 'Trauma-informed Therapy', 'Relationship Counselling'],
  'Amjad Ali Mohammad is a Hyderabad-based therapist with 11 years of experience in anxiety, depression, trauma, relationship issues, career stress, infidelity, and divorce recovery.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/68692f567f8e34a42cb4a7f2.jpeg',
  NULL,
  11,
  'Hyderabad',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 12: Lalitha Ragul
(
  'Lalitha Ragul',
  'lalitha-ragul',
  'premium',
  4900,
  ARRAY['Couples Therapy', 'Family Counselling', 'Parenting', 'Child Counselling', 'Adolescent Counselling'],
  ARRAY['Tamil', 'Malayalam', 'Hindi', 'English'],
  ARRAY['Family Systems Therapy', 'Couples Therapy', 'Child & Adolescent Therapy'],
  'Lalitha Ragul is a Chennai-based therapist with 8+ years of experience in couple therapy, family counselling, parenting, and child & adolescent counselling.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa9eedab54a670cecc.jpeg',
  NULL,
  8,
  'Chennai',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 13: Muthulakshmi Balasubramanian
(
  'Muthulakshmi Balasubramanian',
  'muthulakshmi-balasubramanian',
  'premium',
  4700,
  ARRAY['Depression', 'Anxiety', 'Relationship Counselling', 'Sleep Problems', 'Loneliness', 'Grief', 'Stress Management', 'Anger Management', 'Phobias'],
  ARRAY['Tamil', 'English'],
  ARRAY['CBT', 'Grief Counselling', 'Stress Management'],
  'Muthulakshmi Balasubramanian is a Chennai-based therapist with 6 years of experience in depression, anxiety, relationship counselling, sleep problems, loneliness, grief, stress and anger management, and phobias.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa9c75a7ac8f907d3e.jpeg',
  NULL,
  6,
  'Chennai',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 14: Shruti Garg
(
  'Shruti Garg',
  'shruti-garg',
  'premium',
  4700,
  ARRAY['Trauma', 'Queer Affirmative Therapy', 'Creative Arts Therapy', 'Grief', 'PTSD', 'Anxiety', 'Depression', 'Self-Esteem', 'Neurodivergence'],
  ARRAY['English', 'Haryanvi', 'Hindi'],
  ARRAY['Trauma-focused Therapy', 'Queer Affirmative Therapy', 'Creative Arts Therapy'],
  'Shruti Garg is a Delhi-based therapist with 6+ years of experience in trauma-focused therapy, queer affirmative therapy, and creative arts therapy.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa9dbb37473c07a9eb.jpeg',
  NULL,
  6,
  'Delhi',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 15: Khushboo Sanghavi
(
  'Khushboo Sanghavi',
  'khushboo-sanghavi',
  'premium',
  4400,
  ARRAY['Personal Growth', 'Relationship Issues', 'Family Problems', 'Depression', 'Behavioral Problems', 'Emotional Problems'],
  ARRAY['English', 'Gujarati'],
  ARRAY['Person-Centred Therapy', 'CBT'],
  'Khushboo Sanghavi is a Mumbai-based therapist with 4 years of experience in personal growth, relationship issues, family problems, depression, and behavioral & emotional problems.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa9c75a706b3907d3d.jpeg',
  NULL,
  4,
  'Mumbai',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 16: Shivangi Anil
(
  'Shivangi Anil',
  'shivangi-anil',
  'premium',
  4400,
  ARRAY['Couples Therapy', 'Anxiety', 'Depression', 'Work Stress', 'Burnout'],
  ARRAY['English', 'Hindi'],
  ARRAY['Couples Therapy', 'CBT', 'Stress Management'],
  'Shivangi Anil is a Delhi-based therapist with 5 years of experience in couple therapy, anxiety, depression, work stress, and burnout.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa2ee4856e71c45759.jpeg',
  NULL,
  5,
  'Delhi',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 17: Joshitha Cheppalli
(
  'Joshitha Cheppalli',
  'joshitha-cheppalli',
  'premium',
  4400,
  ARRAY['CBT', 'Mindfulness'],
  ARRAY['English', 'Telugu', 'Tamil'],
  ARRAY['CBT', 'Mindfulness-Based Therapy'],
  'Joshitha Cheppalli is a Hyderabad-based therapist with 4 years of experience specialising in CBT and mindfulness.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa9eedab684270ceca.jpeg',
  NULL,
  4,
  'Hyderabad',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 18: Dimple Jain
(
  'Dimple Jain',
  'dimple-jain',
  'premium',
  3900,
  ARRAY['Anxiety', 'Depression', 'Trauma', 'Relationship Issues', 'Career Stress'],
  ARRAY['English', 'Hindi'],
  ARRAY['CBT', 'Trauma-informed Therapy'],
  'Dimple Jain is an Ahmedabad-based therapist with 3.5 years of experience in anxiety, depression, trauma, relationship issues, and career stress.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/68692f03b1dd8123c43b43e2.jpeg',
  NULL,
  4,
  'Ahmedabad',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 19: Janani K
(
  'Janani K',
  'janani-k',
  'premium',
  3900,
  ARRAY['Anxiety', 'Depression', 'Trauma', 'Relationship Issues', 'Career Stress', 'Infidelity', 'Divorce Recovery'],
  ARRAY['Tamil', 'English'],
  ARRAY['CBT', 'Trauma-informed Therapy', 'Relationship Counselling'],
  'Janani K is a Tamil Nadu-based therapist with 3 years of experience in anxiety, depression, trauma, relationship issues, career stress, infidelity, and divorce recovery.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/68692f35b1dd8141d03b4400.jpeg',
  NULL,
  3,
  'Tamil Nadu',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
),

-- Premium 20: Rizun Sharma
(
  'Rizun Sharma',
  'rizun-sharma',
  'premium',
  4700,
  ARRAY['CBT', 'Anxiety', 'Stress Management', 'Depression', 'OCD', 'Relationship Issues', 'Self-Esteem', 'Suicide Prevention'],
  ARRAY['English', 'Hindi', 'Marathi', 'Marwari'],
  ARRAY['CBT', 'Personality Development', 'Suicide Prevention'],
  'Rizun Sharma is a Mumbai-based therapist with 3+ years of experience in CBT, anxiety, stress & depression, OCD, relationship issues, self-esteem, personality development, and suicide prevention.',
  'https://storage.googleapis.com/msgsndr/m9jCzEyKqM4xlMWTjcgS/media/679b42fa4f0aeb73be63a300.jpeg',
  NULL,
  3,
  'Mumbai',
  'India',
  'Asia/Kolkata',
  '+14254424167',
  NULL,
  TRUE,
  6,
  NULL
);
